Zireael/install/ddl/zireael_lu.sql
Zireael/install/ddl/zireael_library.sql
Zireael/install/ddl/zireael_user.sql
Zireael/install/grants/zireael_lu.sql
Zireael/install/grants/zireael_user.sql
Zireael/install/grants/zireael_library.sql