install/zireael_library/ddl/book_seq.sql
install/zireael_library/ddl/t_books.sql
install/zireael_library/ddl/book_tbi.sql

install/zireael_library/ddl/genre_seq.sql
install/zireael_library/ddl/t_genres.sql
install/zireael_library/ddl/genre_tbi.sql

install/zireael_library/ddl/publisher_seq.sql
install/zireael_library/ddl/t_publishers.sql
install/zireael_library/ddl/publisher_tbi.sql

install/zireael_library/ddl/author_seq.sql
install/zireael_library/ddl/t_authors.sql
install/zireael_library/ddl/author_tbi.sql

install/zireael_library/ddl/t_lnk_books_publishers.sql