grant create session to zireael_role with admin option;
grant create user to zireael_role;
grant alter user to zireael_role;
grant drop user to zireael_role;
grant create tablespace to zireael_role;
grant alter tablespace to zireael_role;
grant drop tablespace to zireael_role;
grant create sequence to zireael_role with admin option;
grant create trigger to zireael_role with admin option;
grant create table to zireael_role with admin option;
grant create role to zireael_role;
grant create procedure to zireael_role with admin option;